services:
  ts-nginx-public:
    env_file:
      - path: ./.env
    image: tailscale/tailscale:latest
    container_name: ts-nginx-public
    # This will ultimately be the hostname for our magic DNS on tailscale
    hostname: nginx-public
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY:-NOT_SET}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/nginx-public.json
    volumes:
      - ./nginx-public-proxy/tailscale/state:/var/lib/tailscale
      - ./nginx-public-proxy/tailscale/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: service:ts-nginx-public
    depends_on:
      - ts-nginx-public
    volumes: 
      - ./nginx-public-proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

networks:
  publicnet:
    driver: bridge

volumes:
  ts-nginx-public:
    driver: local
  nginx-data:
    driver: local

