services:
  ts-nginx-public:
    env_file:
      - path: ./.env
    image: tailscale/tailscale:latest
    container_name: ts-nginx-public
    # This will ultimately be the hostname for our magic DNS on tailscale
    hostname: nginx-public
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY:-NOT_SET}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./nginx-public-proxy/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    networks:
      - publicnet

  nginx:
    image: nginx:latest
    container_name: nginx
    # Bind local 8888 for testing
    ports:
      - 8888:8080
    depends_on:
      - ts-nginx-public
    volumes: 
      - ./nginx-public-proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - publicnet

  ssh-tunnels:
    build: ./ssh-tunnels
    depends_on:
      - ts-nginx-public
      - nginx
    network_mode: service:ts-nginx-public
    command: ["python", "tunnel_manager.py"]


networks:
  publicnet:
    driver: bridge

volumes:
  ts-nginx-public:
    driver: local
  nginx-data:
    driver: local

