services:
  ts-nginx-router:
    env_file:
      - path: ./.env
    image: tailscale/tailscale:latest
    container_name: ts-nginx-router
    # This will ultimately be the hostname for our magic DNS on tailscale
    hostname: nginx-router-docker-public
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY:-NOT_SET}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./nginx-public-proxy/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
    networks:
      - publicnet

  # Primary router for compose stack - mainly used for
  # Routing from HTTPS remote proxy
  nginx-router:
    image: nginx:latest
    container_name: nginx-router
    # Bind local 8888 for testing
    ports:
      - 8888:8080
    depends_on:
      - ts-nginx-public
    volumes: 
      - ./nginx-router/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - publicnet



networks:
  publicnet:
    driver: bridge

volumes:
  ts-nginx-public:
    driver: local
  nginx-data:
    driver: local

